language: rust

matrix:
  include:
    # MSRV
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # MSRV
    - env: TARGET=armv7r-none-eabi
      rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # MSRV
    - env: TARGET=armv7r-none-eabihf
      rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # MSRV
    - env: TARGET=armebv7r-none-eabi
      rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # MSRV
    - env: TARGET=armebv7r-none-eabihf
      rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=armv7r-none-eabi
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=armv7r-none-eabihf
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=armebv7r-none-eabi
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=armebv7r-none-eabihf
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
